### ISSUE TITLE
Executing the code

### ISSUE THREAD

**Issue by sudhanvalalit** [rsouza01/tovsolver#1]
Hi,

Given an EOS (using the ones you provided in python folder), how long does it take to execute the entire code (from data to plotting)? Could you provide a rough estimate? Plus is it possible for you to generalize the code to openmp or openacc format? Probably will help in calculating quickly.

**Comment by rsouza01** [comment]
Dear @sudhanvalalit , it would depend on the "granularity" of the EoS. But even for a EoS file with, say, 100 lines (or central pressures, according to my implementation), I think it would take less tham 2 ou 3 minutes, if so.

Regarding your second questions, I'm afraid not. The fortran code is intended to run for one simple star configuration (rho_0) at a time. So (I guess) it's not possible to paralelize it. BUT, one can reestructure the shell scritpt in order to, instead of calculating 100 star configurations in a queue, calculate 100 (or more, see the first paragraph) at the same time. This I know can be done.

I'm sorry for taking too long to answer, but believe it or not, my mom and my academic career died by the same time you opened this issue.

Cheers.

P.S.: Do not use the Python implementation. It is giving wrong answers. Use the Fortran one (or fix the Python). :-)

**Comment by sudhanvalalit** [comment]
Dear @rsouza01 
I am very sorry for the loss of your mother (May she rest in peace). I am glad you took time off to reply. Thank you very much, one for creating the code and second for answering. I'll try fixing the python code. In the mean time I will use the fortran code for some problems I am studying.  
Regards,

Sudhanva.
